#!/bin/bash

###############################################################################
# CMS Docker Comprehensive Setup Script
# Author: CCYod
# 
# This script automates the full deployment of CMS with orderly service recovery
# and configuration management. Supports fresh installs and updates.
###############################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Helpers
print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[✓]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[!]${NC} $1"; }
print_error() { echo -e "${RED}[✗]${NC} $1"; }
print_step() { echo -e "${CYAN}[STEP]${NC} $1"; }

# Banner
clear
echo -e "${CYAN}"
cat << "EOF"
   ______ __  ______   ____             __             
  / ____//  |/  / ___/  / __ \ ____  ____/ /__ ___  _____
 / /    / /|_/ /\__ \  / / / // __ \/ __  // _ \/ _ \/ ___/
/ /___ / /  / /___/ / / /_/ // /_/ / /_/ //  __/  __/ /    
\____//_/  /_//____/ /_____/ \____/\__,_/ \___/\___/_/     
                                                           
          Modern Deployment & Management
EOF
echo -e "${NC}"

# Check prerequisites
print_step "Checking prerequisites..."
PREREQS=("docker" "docker-compose" "openssl" "python3" "curl")
for cmd in "${PREREQS[@]}"; do
    if ! command -v $cmd &> /dev/null; then
        print_error "$cmd is not installed. Please install it first."
        exit 1
    fi
done
print_success "Prerequisites found."

# 0. Detection & Update Logic
IS_UPDATE=false
if [ -f .env.core ]; then
    IS_UPDATE=true
    print_warning "Existing configuration (.env.core) detected. Switching to UPDATE mode."
    
    # Load existing variables
    DETECTED_DB_PASS=$(grep "^POSTGRES_PASSWORD=" .env.core | cut -d '=' -f2-)
    DETECTED_IP=$(grep "^PUBLIC_IP=" .env.core | cut -d '=' -f2-)
    DETECTED_DEPLOY_TYPE=$(grep "^DEPLOYMENT_TYPE=" .env.admin 2>/dev/null | cut -d '=' -f2- || echo "img")
    
    print_info "Detected Public IP: $DETECTED_IP"
    print_info "Detected Strategy: $([ "$DETECTED_DEPLOY_TYPE" = "img" ] && echo "Pre-built Images" || echo "Source Build")"
fi

# 1. Deployment Choice
echo ""
print_step "Deployment Strategy"
if [ "$IS_UPDATE" = "true" ]; then
    echo "Current strategy is: $([ "$DETECTED_DEPLOY_TYPE" = "img" ] && echo "Pre-built Images" || echo "Source Build")"
    read -p "Keep existing strategy? (y/n) [y]: " KEEP_STRAT
    KEEP_STRAT=${KEEP_STRAT:-y}
    if [ "$KEEP_STRAT" = "y" ]; then
        DEPLOY_TYPE=$DETECTED_DEPLOY_TYPE
    else
        echo "1) PRE-BUILT IMAGES"
        echo "2) BUILD FROM SOURCE"
        read -p "Select new strategy [1]: " STRATEGY_CHOICE
        STRATEGY_CHOICE=${STRATEGY_CHOICE:-1}
        DEPLOY_TYPE=$([ "$STRATEGY_CHOICE" = "1" ] && echo "img" || echo "src")
    fi
else
    echo "How would you like to deploy CMS?"
    echo "1) PRE-BUILT IMAGES (Fastest, recommended for production)"
    echo "2) BUILD FROM SOURCE (Allows custom code changes, takes longer)"
    read -p "Select strategy [1]: " STRATEGY_CHOICE
    STRATEGY_CHOICE=${STRATEGY_CHOICE:-1}
    DEPLOY_TYPE=$([ "$STRATEGY_CHOICE" = "1" ] && echo "img" || echo "src")
fi

# 2. Network Configuration
echo ""
print_step "Network Configuration"
if [ "$IS_UPDATE" = "true" ]; then
    read -p "Use detected IP ($DETECTED_IP)? (y/n) [y]: " USE_OLD_IP
    USE_OLD_IP=${USE_OLD_IP:-y}
    if [ "$USE_OLD_IP" = "y" ]; then
        PUBLIC_IP=$DETECTED_IP
    else
        NEW_DET_IP=$(curl -s -4 ifconfig.me || echo "127.0.0.1")
        read -p "Enter new Public IP [$NEW_DET_IP]: " PUBLIC_IP
        PUBLIC_IP=${PUBLIC_IP:-$NEW_DET_IP}
    fi
else
    DETECTED_IP=$(curl -s -4 ifconfig.me || echo "127.0.0.1")
    read -p "Public IP of this server [$DETECTED_IP]: " PUBLIC_IP
    PUBLIC_IP=${PUBLIC_IP:-$DETECTED_IP}
fi

# 3. Database Configuration
echo ""
print_step "Database Configuration"
if [ "$IS_UPDATE" = "true" ]; then
    print_info "Reusing existing database credentials to prevent data loss."
    DB_PASS=$DETECTED_DB_PASS
else
    read -p "Database password [generate random]: " DB_PASS
    if [ -z "$DB_PASS" ]; then
        DB_PASS=$(openssl rand -base64 12 | tr -d "=+/" | cut -c1-12)
        print_info "Generated password: $DB_PASS"
    fi
fi

# 4. Environment Generation
echo ""
print_step "Generating Configuration Files..."

# Prepare .env.core
cat > .env.core << EOF
# Generated by setup.sh
PUBLIC_IP=$PUBLIC_IP
POSTGRES_DB=cmsdb
POSTGRES_USER=cmsuser
POSTGRES_PASSWORD=$DB_PASS
POSTGRES_PORT_EXTERNAL=5432
POSTGRES_HOST_AUTH_METHOD=md5
CMS_CONFIG=/usr/local/etc/cms.toml
LOG_SERVICE_SHARD=0
RESOURCE_SERVICE_SHARD=0
SCORING_SERVICE_SHARD=0
EVALUATION_SERVICE_SHARD=0
PROXY_SERVICE_SHARD=0
CHECKER_SERVICE_SHARD=0
EOF

# Prepare .env.admin
cat > .env.admin << EOF
# Generated by setup.sh
DEPLOYMENT_TYPE=$DEPLOY_TYPE
VITE_API_URL=http://$PUBLIC_IP:8889
SERVER_BASE_URL=http://$PUBLIC_IP
ADMIN_NEXT_PORT_EXTERNAL=8891
ADMIN_NEXT_DOMAIN=admin-next.cms.local
ADMIN_PORT_EXTERNAL=8889
ADMIN_DOMAIN=admin.cms.local
RANKING_PORT_EXTERNAL=8890
RANKING_DOMAIN=ranking.cms.local
RANKING_USERNAME=admin
RANKING_PASSWORD=adminpass
ADMIN_COOKIE_DURATION=36000
EOF

# Prepare .env.contest (Preserve multi-contest config and secret key if update)
if [ "$IS_UPDATE" = "true" ]; then
    EXISTING_MULTI_CONFIG=$(grep "^CONTESTS_DEPLOY_CONFIG=" .env.contest 2>/dev/null | cut -d '=' -f2- || echo '[{"id":1,"port":8888,"domain":"contest.cms.local"}]')
    SECRET_KEY=$(grep "^SECRET_KEY=" .env.contest 2>/dev/null | cut -d '=' -f2-)
else
    EXISTING_MULTI_CONFIG='[{"id":1,"port":8888,"domain":"contest.cms.local"}]'
    SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(16))')
fi

cat > .env.contest << EOF
# Generated by setup.sh
# Multi-contest configuration (JSON array)
CONTESTS_DEPLOY_CONFIG=$EXISTING_MULTI_CONFIG
SECRET_KEY=$SECRET_KEY
COOKIE_DURATION=10800
ACCESS_METHOD=public_port
EOF

# Prepare .env.worker
cat > .env.worker << EOF
# Generated by setup.sh
WORKER_SHARD=0
WORKER_REPLICAS=1
WORKER_MEMORY_LIMIT=2G
WORKER_CPU_LIMIT=2
EOF

# Run Makefile env to combine them and inject into cms.toml
make env
print_success "Environment files and cms.toml generated."

# 5. Service Deployment (Core)
echo ""
print_step "Deploying Core Services..."
if [ "$DEPLOY_TYPE" = "img" ]; then
    make core-img
else
    make core
fi

print_info "Waiting for database to be healthy..."
# Wait for database healthcheck
until [ "$(docker inspect -f '{{.State.Health.Status}}' cms-database 2>/dev/null)" == "healthy" ]; do
    printf "."
    sleep 2
done
echo ""
print_success "Database is ready."

# 6. Database Initialization / Update
echo ""
print_step "Updating Database Schema..."
# cmsInitDB is non-destructive (it won't wipe tables)
docker exec -it cms-log-service cmsInitDB || print_info "Note: cmsInitDB skipped some steps (likely already initialized)."
make prisma-sync
# Patch schema (idempotent)
docker exec -i cms-database psql -U cmsuser -d cmsdb < scripts/fix_db_schema.sql
print_success "Database updated and schema patched."

# 7. Deploy Admin Services
echo ""
print_step "Deploying Admin Panel..."
if [ "$DEPLOY_TYPE" = "img" ]; then
    make admin-img
else
    make admin
fi
print_success "Admin Panel deployed."

# 8. Deploy Workers & Contest
echo ""
print_step "Deploying Workers and Contest Web Server..."
if [ "$DEPLOY_TYPE" = "img" ]; then
    make worker-img
    make contest-img
else
    make worker
    make contest
fi
print_success "Contest services deployed."

# 9. Create Admin Account
if [ "$IS_UPDATE" != "true" ]; then
    echo ""
    print_step "User Configuration"
    read -p "Create a superadmin account now? (y/n) [y]: " CREATE_ADMIN
    CREATE_ADMIN=${CREATE_ADMIN:-y}
    if [ "$CREATE_ADMIN" = "y" ]; then
        make admin-create
    fi
fi

# Final Summary
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}             Setup Completed Successfully!                  ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "🚀 Services are now available at:"
echo -e "   - ${CYAN}Admin UI (New):${NC}   http://$PUBLIC_IP:8891"
echo -e "   - ${CYAN}Contest UI:${NC}      http://$PUBLIC_IP:8888"
echo -e "   - ${CYAN}Admin API/Legacy:${NC} http://$PUBLIC_IP:8889"
echo -e "   - ${CYAN}Ranking:${NC}        http://$PUBLIC_IP:8890"
echo ""
print_info "Note: The Admin UI allows you to switch contests and manage workers."
print_info "Saving changes in the Admin UI will automatically restart the required services."
echo ""
print_success "Documentation: docs/DEPENDENCIES.md"
print_success "Setup script saved your configuration in .env.* files"
echo ""