use super::{
    CommandSpec, ARGS_DOMAIN_SETUP, ARGS_DOMAIN_VERB, ARGS_FUNNEL, ARGS_NONE, ARGS_TAILSCALE,
    ARGS_WORKER, SCRIPT_CONFIG_SYNC, SCRIPT_CREATE_CONTESTS, SCRIPT_DOMAIN, SCRIPT_FUNNEL,
    SCRIPT_TAILSCALE_SERVE, SCRIPT_UPDATE_SERVER, SCRIPT_WORKER_CGROUP, SCRIPT_WORKER_TUI,
};
use crate::core::dispatch::{DispatchKey, DispatchTarget};

pub const FLEET_CATALOG: &[CommandSpec] = &[
    CommandSpec {
        key: DispatchKey::WorkerEdit,
        target: DispatchTarget::Script(SCRIPT_WORKER_TUI),
        args: ARGS_WORKER,
        about: "Worker edit",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::WorkerDeploy,
        target: DispatchTarget::Script(SCRIPT_WORKER_TUI),
        args: ARGS_WORKER,
        about: "Worker deploy",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::WorkerStop,
        target: DispatchTarget::Script(SCRIPT_WORKER_TUI),
        args: ARGS_WORKER,
        about: "Worker stop",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::WorkerList,
        target: DispatchTarget::Script(SCRIPT_WORKER_TUI),
        args: ARGS_WORKER,
        about: "Worker list",
        requires_tty: false,
        requires_sudo: false,
        capture_output: true,
    },
    CommandSpec {
        key: DispatchKey::WorkerAttach,
        target: DispatchTarget::Script(SCRIPT_WORKER_TUI),
        args: ARGS_WORKER,
        about: "Worker attach",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::WorkerCgroup,
        target: DispatchTarget::Script(SCRIPT_WORKER_CGROUP),
        args: ARGS_NONE,
        about: "Worker cgroup",
        requires_tty: true,
        requires_sudo: true,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::TailscaleSetup,
        target: DispatchTarget::Script(SCRIPT_TAILSCALE_SERVE),
        args: ARGS_TAILSCALE,
        about: "Tailscale setup",
        requires_tty: false,
        requires_sudo: false,
        capture_output: true,
    },
    CommandSpec {
        key: DispatchKey::TailscaleStatus,
        target: DispatchTarget::Script(SCRIPT_TAILSCALE_SERVE),
        args: ARGS_TAILSCALE,
        about: "Tailscale status",
        requires_tty: false,
        requires_sudo: false,
        capture_output: true,
    },
    CommandSpec {
        key: DispatchKey::TailscaleRemove,
        target: DispatchTarget::Script(SCRIPT_TAILSCALE_SERVE),
        args: ARGS_TAILSCALE,
        about: "Tailscale remove",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::FunnelSetup,
        target: DispatchTarget::Script(SCRIPT_FUNNEL),
        args: ARGS_FUNNEL,
        about: "Funnel setup",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::FunnelPasswd,
        target: DispatchTarget::Script(SCRIPT_FUNNEL),
        args: ARGS_FUNNEL,
        about: "Funnel passwd",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::FunnelRemove,
        target: DispatchTarget::Script(SCRIPT_FUNNEL),
        args: ARGS_FUNNEL,
        about: "Funnel remove",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::FunnelStatus,
        target: DispatchTarget::Script(SCRIPT_FUNNEL),
        args: ARGS_FUNNEL,
        about: "Funnel status",
        requires_tty: false,
        requires_sudo: false,
        capture_output: true,
    },
    CommandSpec {
        key: DispatchKey::ContestCreate,
        target: DispatchTarget::Script(SCRIPT_CREATE_CONTESTS),
        args: ARGS_NONE,
        about: "Contest create",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::UpdateServer,
        target: DispatchTarget::Script(SCRIPT_UPDATE_SERVER),
        args: ARGS_NONE,
        about: "Shard-aware server update",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::DomainSetup,
        target: DispatchTarget::Script(SCRIPT_DOMAIN),
        args: ARGS_DOMAIN_SETUP,
        about: "Domain setup",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::DomainStatus,
        target: DispatchTarget::Script(SCRIPT_DOMAIN),
        args: ARGS_DOMAIN_VERB,
        about: "Domain status",
        requires_tty: false,
        requires_sudo: false,
        capture_output: true,
    },
    CommandSpec {
        key: DispatchKey::DomainRenew,
        target: DispatchTarget::Script(SCRIPT_DOMAIN),
        args: ARGS_DOMAIN_VERB,
        about: "Domain renew",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
    CommandSpec {
        key: DispatchKey::DomainPreflight,
        target: DispatchTarget::Script(SCRIPT_DOMAIN),
        args: ARGS_DOMAIN_VERB,
        about: "Domain preflight",
        requires_tty: false,
        requires_sudo: false,
        capture_output: true,
    },
    CommandSpec {
        key: DispatchKey::ConfigSync,
        target: DispatchTarget::Script(SCRIPT_CONFIG_SYNC),
        args: ARGS_NONE,
        about: "Config sync",
        requires_tty: true,
        requires_sudo: false,
        capture_output: false,
    },
];
