import { readdir, realpath, stat } from 'node:fs/promises';
import path from 'node:path';
import { getRepoRoot } from '@/lib/repo-root';

export type BackupArchiveKind = 'db' | 'volume' | 'sql';

export interface BackupArchive {
  readonly name: string;
  readonly kind: BackupArchiveKind;
  readonly relativePath: string;
  readonly sizeBytes: number;
  readonly modifiedAt: string;
}

/**
 * Backup filenames are generated by scripts/__backup.sh, so this allowlist only
 * has to admit what that script writes. It admits no separator, which is what
 * makes `..`, `../secrets.dump` and `/etc/passwd` fail before any path is built.
 */
const ARCHIVE_NAME_PATTERN = /^[A-Za-z0-9._-]+\.(dump|tar\.gz|sql\.gz)$/;

const MAX_ARCHIVES = 200;

/** Mirrors the layout scripts/__backup.sh writes: db dumps, volume tars, manifest at the root. */
const ARCHIVE_DIRECTORIES: readonly string[] = ['db', 'volumes', '.'];

export function getBackupRoot(): string {
  const configured = process.env.BACKUP_DIR?.trim();
  if (configured) return path.resolve(configured);
  return path.join(getRepoRoot(), 'backups');
}

export function isArchiveName(name: string): boolean {
  return ARCHIVE_NAME_PATTERN.test(name);
}

export function archiveKind(name: string): BackupArchiveKind | null {
  if (name.endsWith('.tar.gz')) return 'volume';
  if (name.endsWith('.dump')) return 'db';
  if (name.endsWith('.sql.gz')) return 'sql';
  return null;
}

export function sortNewestFirst(archives: readonly BackupArchive[]): BackupArchive[] {
  return [...archives].sort((left, right) => right.modifiedAt.localeCompare(left.modifiedAt) || right.name.localeCompare(left.name));
}

export function capArchives(archives: readonly BackupArchive[], limit: number = MAX_ARCHIVES): BackupArchive[] {
  return sortNewestFirst(archives).slice(0, Math.max(limit, 0));
}

function toArchive(name: string, directory: string, root: string, modifiedAtMs: number, sizeBytes: number): BackupArchive | null {
  const kind = archiveKind(name);
  if (kind === null) return null;
  return {
    name,
    kind,
    relativePath: path.relative(root, path.join(directory, name)),
    sizeBytes,
    modifiedAt: new Date(modifiedAtMs).toISOString(),
  };
}

async function readArchiveDirectory(directory: string, root: string): Promise<BackupArchive[]> {
  const entries = await readdir(directory, { withFileTypes: true }).catch(() => []);
  const archives: BackupArchive[] = [];
  for (const entry of entries) {
    if (!entry.isFile() || !isArchiveName(entry.name)) continue;
    const info = await stat(path.join(directory, entry.name));
    const archive = toArchive(entry.name, directory, root, info.mtimeMs, info.size);
    if (archive !== null) archives.push(archive);
  }
  return archives;
}

export async function listArchives(limit: number = MAX_ARCHIVES): Promise<BackupArchive[]> {
  const root = await realpath(getBackupRoot()).catch(() => null);
  if (root === null) return [];
  const perDirectory = await Promise.all(ARCHIVE_DIRECTORIES.map((directory) => readArchiveDirectory(path.join(root, directory), root)));
  return capArchives(perDirectory.flat(), limit);
}

function isInsideRoot(root: string, candidate: string): boolean {
  const relative = path.relative(root, candidate);
  return relative.length > 0 && !relative.startsWith('..') && !path.isAbsolute(relative);
}

/**
 * Resolves a requested archive to a real path inside the backup root. The name
 * pattern already excludes separators; the realpath comparison additionally
 * refuses a symlink planted inside the backup directories that points outside it.
 */
export async function resolveArchivePath(name: string): Promise<string | null> {
  if (!isArchiveName(name)) return null;
  const root = await realpath(getBackupRoot()).catch(() => null);
  if (root === null) return null;
  for (const directory of ARCHIVE_DIRECTORIES) {
    const resolved = await realpath(path.join(root, directory, name)).catch(() => null);
    if (resolved !== null && isInsideRoot(root, resolved)) return resolved;
  }
  return null;
}