import type { FieldPermissionDef } from '@/lib/field-permissions';

// Why a separate file: field-permissions.ts must stay under 250 lines.
// These tables merge into FIELD_PERMISSION_MAP there; importers keep one path.
export const EXTRA_FIELD_PERMISSION_MAP: Record<string, Record<string, FieldPermissionDef>> = {
  evaluations: {
    id: { read: 'evaluation:read' },
    submission_id: { read: 'evaluation:read' },
    dataset_id: { read: 'evaluation:read' },
    testcase_id: { read: 'evaluation:read' },
    outcome: { read: 'evaluation:read' },
    text: { read: 'evaluation:read' },
    execution_time: { read: 'evaluation:read' },
    execution_memory: { read: 'evaluation:read' },
  },
  executables: {
    id: { read: 'executable:read' },
    submission_id: { read: 'executable:read' },
    dataset_id: { read: 'executable:read' },
    filename: { read: 'executable:read' },
    digest: { read: 'executable:read' },
  },
  files: {
    id: { read: 'file:read' },
    submission_id: { read: 'file:read' },
    filename: { read: 'file:read' },
    digest: { read: 'file:read' },
  },
  submission_results: {
    submission_id: { read: 'submissionresult:read' },
    dataset_id: { read: 'submissionresult:read' },
    score: { read: 'submissionresult:read' },
    public_score: { read: 'submissionresult:read' },
    compilation_outcome: { read: 'submissionresult:read' },
    evaluation_outcome: { read: 'submissionresult:read' },
    compilation_text: { read: 'submissionresult:read' },
    compilation_stdout: { read: 'submissionresult:read' },
    compilation_stderr: { read: 'submissionresult:read' },
  },
  tokens: {
    id: { read: 'token:read' },
    submission_id: { read: 'token:read' },
    timestamp: { read: 'token:read' },
  },
  user_tests: {
    id: { read: 'usertest:read' },
    participation_id: { read: 'usertest:read' },
    task_id: { read: 'usertest:read' },
    language: { read: 'usertest:read' },
    input: { read: 'usertest:read' },
    timestamp: { read: 'usertest:read' },
  },
  permissions: {
    key: { read: 'permission:read' },
    module: { read: 'permission:read' },
    verb: { read: 'permission:read' },
    description: { read: 'permission:read' },
  },
  groups: {
    id: { read: 'group:read' },
    name: { read: 'group:read' },
    description: { read: 'group:read' },
  },
  contests: {
    id: { read: 'contest:read' },
    name: { read: 'contest:read', update: 'contest:update' },
    description: { read: 'contest:read', update: 'contest:update' },
    allowed_localizations: { read: 'contest:read', update: 'contest:update' },
    languages: { read: 'contest:read', update: 'contest:update' },
    submissions_download_allowed: { read: 'contest:read', update: 'contest:update' },
    allow_questions: { read: 'contest:read', update: 'contest:update' },
    allow_user_tests: { read: 'contest:read', update: 'contest:update' },
    allow_unofficial_submission_before_analysis_mode: { read: 'contest:read', update: 'contest:update' },
    block_hidden_participations: { read: 'contest:read', update: 'contest:update' },
    allow_password_authentication: { read: 'contest:read', update: 'contest:update' },
    allow_registration: { read: 'contest:read', update: 'contest:update' },
    ip_restriction: { read: 'contest:read', update: 'contest:update' },
    ip_autologin: { read: 'contest:read', update: 'contest:update' },
    token_mode: { read: 'contest:read', update: 'contest:update' },
    token_max_number: { read: 'contest:read', update: 'contest:update' },
    token_min_interval: { read: 'contest:read', update: 'contest:update' },
    token_gen_initial: { read: 'contest:read', update: 'contest:update' },
    token_gen_number: { read: 'contest:read', update: 'contest:update' },
    token_gen_interval: { read: 'contest:read', update: 'contest:update' },
    token_gen_max: { read: 'contest:read', update: 'contest:update' },
    max_submission_number: { read: 'contest:read', update: 'contest:update' },
    max_user_test_number: { read: 'contest:read', update: 'contest:update' },
    min_submission_interval: { read: 'contest:read', update: 'contest:update' },
    min_submission_interval_grace_period: { read: 'contest:read', update: 'contest:update' },
    min_user_test_interval: { read: 'contest:read', update: 'contest:update' },
    queue_fairness_penalty_seconds: { read: 'contest:read', update: 'contest:update' },
    is_active: { read: 'contest:read', update: 'contest:switch' },
    score_precision: { read: 'contest:read', update: 'contest:update' },
    start: { read: 'contest:read', update: 'contest:update' },
    stop: { read: 'contest:read', update: 'contest:update' },
    timezone: { read: 'contest:read', update: 'contest:update' },
    per_user_time: { read: 'contest:read', update: 'contest:update' },
    analysis_enabled: { read: 'contest:read', update: 'contest:update' },
    analysis_start: { read: 'contest:read', update: 'contest:update' },
    analysis_stop: { read: 'contest:read', update: 'contest:update' },
  },
};
