import { PERMISSION_REGISTRY, type GroupDefinition } from './permission-registry';

// Why a separate file: the eight seeded groups are ~230 lines on their own.
// Registry keeps keys + system-owned docs; this file keeps grants. Importers
// reference this path directly so there is no registry↔groups cycle.
export type { GroupDefinition };

function crud(moduleName: string): string[] {
  return ['list', 'create', 'read', 'update', 'delete'].map((verb) => `${moduleName}:${verb}`);
}

export const DEFAULT_GROUPS: readonly GroupDefinition[] = [
  {
    name: 'Superadmin',
    description: 'Unrestricted access to every permission in the registry.',
    // Why backup:* excluded: backup rights are manual-grant only (per-admin
    // override or direct link), never inherited — not even here. The engine
    // carve-out below keeps the all:all expansion from re-granting them.
    permissions: PERMISSION_REGISTRY.map((definition) => definition.key).filter(
      (key) => !key.startsWith('backup:'),
    ),
  },
  {
    name: 'Contest Manager',
    description: 'Runs contests end to end, from creation through ranking.',
    permissions: [
      ...crud('contest'),
      'contest:switch',
      'task:list',
      'task:create',
      'task:read',
      'task:update',
      'task:delete',
      'task:switch_dataset',
      'participation:list',
      'participation:create',
      'participation:read',
      'participation:update',
      'participation:delete',
      'dataset:list',
      'dataset:read',
      'dataset:switch',
      'statement:list',
      'statement:read',
      'statement:update',
      'submission:list',
      'submission:read',
      'evaluation:list',
      'evaluation:lane_assign',
      'evaluation:lane_move',
      'submissionresult:list',
      'submissionresult:read',
      'attachment:list',
      'attachment:read',
      'ranking:list',
      'ranking:read',
      'ranking:snapshot',
      'testcase:list',
      'testcase:read',
      'user:list',
      'user:read',
      'team:list',
      'team:read',
      'question:list',
      'question:read',
      'question:answer',
      'message:list',
      'message:read',
      'message:send',
      'message:create',
      'announcement:list',
      'announcement:read',
      'announcement:create',
      'announcement:update',
      'announcement:publish',
    ],
  },
  {
    name: 'Problem Setter',
    description: 'Authors tasks, datasets, statements and test data.',
    permissions: [
      ...crud('task'),
      'task:switch_dataset',
      ...crud('dataset'),
      'dataset:switch',
      ...crud('testcase'),
      ...crud('statement'),
      ...crud('attachment'),
      ...crud('evaluation'),
      'contest:list',
      'contest:read',
      'submission:list',
      'submission:read',
      'submissionresult:list',
      'submissionresult:read',
      'executable:list',
      'executable:read',
    ],
  },
  {
    name: 'Judge',
    description: 'Reviews and reprocesses submissions and evaluations.',
    permissions: [
      'contest:list',
      'contest:read',
      'task:list',
      'task:read',
      'submission:list',
      'submission:create',
      'submission:read',
      'submission:rejudge',
      'submission:download',
      'submission:recompute',
      'submissionresult:list',
      'submissionresult:read',
      'submissionresult:delete',
      'evaluation:list',
      'evaluation:read',
      'evaluation:delete',
      'evaluation:lane_assign',
      'evaluation:lane_move',
      'file:list',
      'file:read',
      'token:list',
      'token:read',
      'usertest:list',
      'usertest:read',
      'dataset:list',
      'attachment:list',
      'attachment:read',
      'ranking:list',
      'ranking:read',
      'user:list',
      'user:read',
    ],
  },
  {
    name: 'Viewer',
    description: 'Read-only access to public contest data.',
    permissions: [
      'contest:list',
      'contest:read',
      'task:list',
      'task:read',
      'submission:list',
      'submission:read',
      'submissionresult:list',
      'submissionresult:read',
      'dataset:list',
      'attachment:list',
      'attachment:read',
      'ranking:list',
      'ranking:read',
      'user:list',
      'user:read',
      'team:list',
      'team:read',
      'participation:list',
      'participation:read',
      'announcement:list',
      'announcement:read',
    ],
  },
  {
    name: 'Data Correction',
    description: 'Repairs submissions, evaluations and participant records.',
    permissions: [
      'contest:list',
      'contest:read',
      'submission:list',
      'submission:read',
      'submission:rejudge',
      'submission:download',
      'submission:recompute',
      'submissionresult:list',
      'submissionresult:read',
      'submissionresult:update',
      'submissionresult:delete',
      'evaluation:list',
      'evaluation:read',
      'evaluation:update',
      'evaluation:delete',
      'file:list',
      'file:read',
      'token:list',
      'token:read',
      'usertest:list',
      'usertest:read',
      'user:list',
      'user:read',
      'user:update',
      'team:list',
      'team:create',
      'team:read',
      'team:update',
      'participation:list',
      'participation:create',
      'participation:read',
      'participation:update',
    ],
  },
  {
    name: 'Storage Admin',
    description: 'Manages files, objects and container/service infrastructure.',
    permissions: [
      ...crud('file'),
      ...crud('fsobject'),
      ...crud('attachment'),
      ...crud('executable'),
      'dataset:read',
      'container:read',
      'container:control',
      'service:restart',
      'service:deploy',
      'deployment:list',
      'deployment:read',
      'deployment:deploy',
      // Why: a deploy is only finished once it activates its contest, and activation is gated on
      // contest:switch (lib/services/contests.ts). Whoever may deploy must therefore be able to
      // activate, or the deploy succeeds and its activation fails.
      'contest:switch',
      'resource:list',
      'resource:read',
      'resource:update',
      // No backup:* grants: backup rights are manual-grant only, so no
      // default group carries them. Re-seed prunes stale backup links.
    ],
  },
  {
    name: 'Messaging',
    description: 'Handles clarifications, messages and announcements.',
    permissions: [
      ...crud('message'),
      'message:send',
      ...crud('announcement'),
      'announcement:publish',
      'question:list',
      'question:read',
      'question:answer',
      'question:ignore',
      'user:list',
      'user:read',
      'contest:list',
      'contest:read',
    ],
  },
];
