#!/bin/bash

###############################################################################
# CMS Multi-Contest Compose Generator
# This script generates a docker-compose file for multiple contests
# without requiring heavy dependencies like Python or Bun.
###############################################################################

OUTPUT_FILE="docker-compose.contests.generated.yml"
CONFIG=${CONTESTS_DEPLOY_CONFIG:-"[]"}
# Detect deployment type (img or src)
DEPLOY_TYPE=${DEPLOYMENT_TYPE:-"img"}
CORE_IMAGE="ghcr.io/champyod/cms-docker-core:major-admin-panel"

# Start file content
cat > "$OUTPUT_FILE" << EOF
# AUTO-GENERATED BY scripts/generate-contest-compose.sh
# DO NOT EDIT MANUALLY

services:
EOF

# Extract each JSON object from the array using grep
# This handles [{"id":1,...},{"id":2,...}]
echo "$CONFIG" | grep -o '{[^}]*}' | while read -r line; do
    [ -z "$line" ] && continue

    # Extract values using grep and cut
    ID=$(echo "$line" | grep -oE '"id":[[:space:]]*[0-9]+' | cut -d: -f2 | tr -d '[:space:]')
    PORT=$(echo "$line" | grep -oE '"port":[[:space:]]*[0-9]+' | cut -d: -f2 | tr -d '[:space:]')
    DOMAIN=$(echo "$line" | grep -oE '"domain":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"')
    ACCESS_METHOD=$(echo "$line" | grep -oE '"accessMethod":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"')
    PROTOCOL=$(echo "$line" | grep -oE '"protocol":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"')
    TLS_CERT=$(echo "$line" | grep -oE '"tlsCertPath":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"')
    TLS_KEY=$(echo "$line" | grep -oE '"tlsKeyPath":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"')
    TAILSCALE_DOMAIN=$(echo "$line" | grep -oE '"tailscaleDomain":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"')

    # Defaults
    if [ -z "$DOMAIN" ]; then
        DOMAIN="contest-$ID.cms.local"
    fi
    if [ -z "$ACCESS_METHOD" ]; then
        ACCESS_METHOD="public_ip"
    fi
    if [ -z "$PROTOCOL" ]; then
        PROTOCOL="http"
    fi

    if [ -n "$ID" ] && [ -n "$PORT" ]; then
        cat >> "$OUTPUT_FILE" << EOF
  contest-web-server-$ID:
EOF
        if [ "$DEPLOY_TYPE" = "img" ]; then
            echo "    image: $CORE_IMAGE" >> "$OUTPUT_FILE"
        else
            cat >> "$OUTPUT_FILE" << EOF
    build:
      context: .
      dockerfile: Dockerfile
EOF
        fi

        cat >> "$OUTPUT_FILE" << EOF
    container_name: cms-contest-web-server-$ID
    restart: on-failure:5
    environment:
      CMS_CONFIG: \${CMS_CONFIG:-/usr/local/etc/cms.toml}
      SERVICE_TYPE: ContestWebServer
      SERVICE_SHARD: 0
      CONTEST_LISTEN_PORT: 8888
      CONTEST_LISTEN_ADDRESS: 0.0.0.0
      CONTEST_ID: $ID
      SECRET_KEY: \${SECRET_KEY}
      COOKIE_DURATION: \${COOKIE_DURATION:-10800}
      MAX_SUBMISSION_LENGTH: \${MAX_SUBMISSION_LENGTH:-100000}
      MAX_INPUT_LENGTH: \${MAX_INPUT_LENGTH:-5000000}
      SUBMIT_LOCAL_COPY: \${SUBMIT_LOCAL_COPY:-true}
      NUM_PROXIES_USED: \${NUM_PROXIES_USED:-1}
    volumes:
      - ./config/cms.toml:/usr/local/etc/cms.toml:ro
      - cms-logs:/var/local/log/cms
      - cms-cache:/var/local/cache/cms
      - cms-data:/var/local/lib/cms
      - cms-submissions-$ID:/var/local/lib/cms/submissions
EOF

        # Add TLS certificate volumes if HTTPS enabled
        if [ "$PROTOCOL" = "https" ] && [ -n "$TLS_CERT" ] && [ -n "$TLS_KEY" ]; then
            echo "      - $TLS_CERT:/etc/ssl/certs/contest.crt:ro" >> "$OUTPUT_FILE"
            echo "      - $TLS_KEY:/etc/ssl/private/contest.key:ro" >> "$OUTPUT_FILE"
        fi

        cat >> "$OUTPUT_FILE" << EOF
    networks:
      - cms-network
EOF

        # Port binding based on access method
        if [ "$ACCESS_METHOD" = "public_ip" ]; then
            echo "    ports:" >> "$OUTPUT_FILE"
            echo "      - \"0.0.0.0:$PORT:8888\"" >> "$OUTPUT_FILE"
        elif [ "$ACCESS_METHOD" = "tailscale" ] && [ -n "$TAILSCALE_DOMAIN" ]; then
            # Bind to Tailscale IP if available
            TAILSCALE_IP=\${TAILSCALE_IP:-127.0.0.1}
            echo "    ports:" >> "$OUTPUT_FILE"
            echo "      - \"\$TAILSCALE_IP:$PORT:8888\"" >> "$OUTPUT_FILE"
        elif [ "$ACCESS_METHOD" = "domain" ]; then
            # No port binding, only accessible via reverse proxy
            echo "    expose:" >> "$OUTPUT_FILE"
            echo "      - \"8888\"" >> "$OUTPUT_FILE"
        fi

        cat >> "$OUTPUT_FILE" << EOF
    privileged: true
    cgroup: host
    command: >
      sh -c "sleep 10 && cmsContestWebServer 0 -c $ID"
    labels:
      - "traefik.enable=true"
EOF

        # Traefik router configuration
        if [ "$PROTOCOL" = "https" ]; then
            cat >> "$OUTPUT_FILE" << EOF
      - "traefik.http.routers.cms-contest-$ID.rule=Host(\`$DOMAIN\`)"
      - "traefik.http.routers.cms-contest-$ID.entrypoints=websecure"
      - "traefik.http.routers.cms-contest-$ID.tls=true"
EOF
            if [ -n "$TLS_CERT" ] && [ -n "$TLS_KEY" ]; then
                cat >> "$OUTPUT_FILE" << EOF
      - "traefik.http.routers.cms-contest-$ID.tls.certresolver=custom"
EOF
            else
                cat >> "$OUTPUT_FILE" << EOF
      - "traefik.http.routers.cms-contest-$ID.tls.certresolver=letsencrypt"
EOF
            fi
        else
            cat >> "$OUTPUT_FILE" << EOF
      - "traefik.http.routers.cms-contest-$ID.rule=Host(\`$DOMAIN\`)"
      - "traefik.http.routers.cms-contest-$ID.entrypoints=web"
EOF
        fi

        cat >> "$OUTPUT_FILE" << EOF
      - "traefik.http.services.cms-contest-$ID.loadbalancer.server.port=8888"

  # Per-Contest RankingWebServer for Contest $ID
  ranking-web-server-$ID:
EOF
        if [ "$DEPLOY_TYPE" = "img" ]; then
            echo "    image: $CORE_IMAGE" >> "$OUTPUT_FILE"
        else
            cat >> "$OUTPUT_FILE" << EOF
    build:
      context: .
      dockerfile: Dockerfile
EOF
        fi

        cat >> "$OUTPUT_FILE" << EOF
    container_name: cms-ranking-web-server-$ID
    restart: on-failure:5
    environment:
      CMS_RANKING_CONFIG: \${CMS_RANKING_CONFIG:-/usr/local/etc/cms_ranking.toml}
      RANKING_LISTEN_PORT: 8890
      RANKING_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./config/cms_ranking.toml:/usr/local/etc/cms_ranking.toml:ro
      - cms-logs:/var/local/log/cms
      - cms-ranking-data-$ID:/var/local/lib/cms/ranking
    networks:
      - cms-network
    ports:
      - "$((8890 + ID)):8890"
    command: >
      sh -c "sleep 10 && cmsRankingWebServer"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-ranking-$ID.rule=Host(\`ranking-$ID.\${DOMAIN:-cms.local}\`)"
      - "traefik.http.services.cms-ranking-$ID.loadbalancer.server.port=8890"
EOF
    fi
done

if [ $(grep -c "contest-web-server-" "$OUTPUT_FILE") -eq 0 ]; then
    echo "  # No contests configured. Add instances via Admin UI." >> "$OUTPUT_FILE"
fi

# Add footer
cat >> "$OUTPUT_FILE" << EOF

networks:
  cms-network:
    external: true
    name: cms-network

volumes:
  cms-logs:
    external: true
    name: cms-logs
  cms-cache:
    external: true
    name: cms-cache
  cms-data:
    external: true
    name: cms-data
EOF

# Add generated volumes
echo "$CONFIG" | grep -o '{[^}]*}' | while read -r line; do
    ID=$(echo "$line" | grep -oE '"id":[[:space:]]*[0-9]+' | cut -d: -f2 | tr -d '[:space:]')
    if [ -n "$ID" ]; then
        echo "  cms-submissions-$ID:" >> "$OUTPUT_FILE"
        echo "    name: cms-submissions-contest-$ID" >> "$OUTPUT_FILE"
        echo "  cms-ranking-data-$ID:" >> "$OUTPUT_FILE"
        echo "    name: cms-ranking-data-contest-$ID" >> "$OUTPUT_FILE"
    fi
done

echo "Successfully generated $OUTPUT_FILE"