#!/usr/bin/env bun
import { write } from "bun";

const CONFIG_JSON = process.env.CONTESTS_DEPLOY_CONFIG || "[]";
const OUTPUT_FILE = "docker-compose.contests.generated.yml";

interface ContestEntry {
  id: number;
  port: number;
  domain?: string;
}

async function generateCompose() {
  let config: ContestEntry[] = [];
  try {
    config = JSON.parse(CONFIG_JSON);
  } catch (e) {
    console.error("Invalid CONTESTS_DEPLOY_CONFIG JSON. Using empty array.");
  }

  let services = "";
  let volumes = "";

  for (const entry of config) {
    const { id, port, domain = `contest-${id}.cms.local` } = entry;
    if (!id || !port) continue;

    services += `
  contest-web-server-${id}:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-contest-web-server-${id}
    restart: unless-stopped
    environment:
      CMS_CONFIG: ${process.env.CMS_CONFIG || "/usr/local/etc/cms.toml"}
      SERVICE_TYPE: ContestWebServer
      SERVICE_SHARD: 0
      CONTEST_LISTEN_PORT: 8888
      CONTEST_LISTEN_ADDRESS: 0.0.0.0
      CONTEST_ID: ${id}
      SECRET_KEY: ${process.env.SECRET_KEY}
      COOKIE_DURATION: ${process.env.COOKIE_DURATION || "10800"}
      MAX_SUBMISSION_LENGTH: ${process.env.MAX_SUBMISSION_LENGTH || "100000"}
      MAX_INPUT_LENGTH: ${process.env.MAX_INPUT_LENGTH || "5000000"}
      SUBMIT_LOCAL_COPY: ${process.env.SUBMIT_LOCAL_COPY || "true"}
      NUM_PROXIES_USED: ${process.env.NUM_PROXIES_USED || "1"}
    volumes:
      - ./config/cms.toml:/usr/local/etc/cms.toml:ro
      - cms-logs:/var/local/log/cms
      - cms-cache:/var/local/cache/cms
      - cms-data:/var/local/lib/cms
      - cms-submissions-${id}:/var/local/lib/cms/submissions
    networks:
      - cms-network
    ports:
      - "${port}:8888"
    privileged: true
    cgroup: host
    command: >
      sh -c "sleep 10 && cmsContestWebServer 0 -c ${id}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-contest-${id}.rule=Host(\
${domain}\")"
      - "traefik.http.services.cms-contest-${id}.loadbalancer.server.port=8888"
`;

    volumes += `
  cms-submissions-${id}:
    name: cms-submissions-contest-${id}
`;
  }

  const content = `version: '3.8'

# AUTO-GENERATED BY scripts/generate-contest-compose.ts
# DO NOT EDIT MANUALLY

services:${services || "\n  # No contests configured"}

networks:
  cms-network:
    external: true
    name: cms-network

volumes:
  cms-logs:
    external: true
    name: cms-logs
  cms-cache:
    external: true
    name: cms-cache
  cms-data:
    external: true
    name: cms-data
${volumes}
`;

  await write(OUTPUT_FILE, content);
  console.log(`Successfully generated ${OUTPUT_FILE} with ${config.length} contests.`);
}

generateCompose();
