#!/usr/bin/env python3
import os
import json
import yaml
from pathlib import Path

def generate():
    env_contest = Path(".env.contest")
    if not env_contest.exists():
        print("No .env.contest found, skipping generation.")
        return

    # Extract CONTESTS_DEPLOY_CONFIG from .env.contest
    deploy_config_str = ""
    with open(env_contest, "r") as f:
        for line in f:
            if line.startswith("CONTESTS_DEPLOY_CONFIG="):
                deploy_config_str = line.split("=", 1)[1].strip()
                break
    
    if not deploy_config_str:
        print("CONTESTS_DEPLOY_CONFIG not found in .env.contest.")
        return

    try:
        deploy_config = json.loads(deploy_config_str)
    except json.JSONDecodeError as e:
        print(f"Failed to parse CONTESTS_DEPLOY_CONFIG: {e}")
        return

    if not isinstance(deploy_config, list):
        print("CONTESTS_DEPLOY_CONFIG is not a list.")
        return

    # Base compose structure
    compose = {
        "version": "3.8",
        "services": {},
        "networks": {
            "cms-network": {
                "external": True,
                "name": "cms-network"
            }
        },
        "volumes": {
            "cms-logs": {"external": True, "name": "cms-logs"},
            "cms-cache": {"external": True, "name": "cms-cache"},
            "cms-data": {"external": True, "name": "cms-data"},
            "cms-submissions": {"name": "cms-submissions-contests"}
        }
    }

    common_volumes = [
        "./config/cms.toml:/usr/local/etc/cms.toml:ro",
        "cms-logs:/var/local/log/cms",
        "cms-cache:/var/local/cache/cms",
        "cms-data:/var/local/lib/cms",
        "cms-submissions:/var/local/lib/cms/submissions"
    ]

    # Detect deployment type
    deploy_type = "img"
    for env_file in [".env.admin", ".env.core"]:
        if Path(env_file).exists():
            with open(env_file, "r") as f:
                for line in f:
                    if line.startswith("DEPLOYMENT_TYPE="):
                        deploy_type = line.split("=", 1)[1].strip()
                        break
    
    image_name = "ghcr.io/champyod/cms-docker-core:major-admin-panel" if deploy_type == "img" else "cms-core:latest"

    for i, item in enumerate(deploy_config):
        contest_id = item.get("id")
        port = item.get("port")
        if not contest_id or not port:
            continue

        svc_name = f"cms-contest-web-server-{contest_id}"
        
        service = {
            "image": image_name,
            "container_name": svc_name,
            "restart": "on-failure:5",
            "environment": {
                "CMS_CONFIG": "/usr/local/etc/cms.toml",
                "SERVICE_TYPE": "ContestWebServer",
                "SERVICE_SHARD": i, # Unique shard for registry
                "CONTEST_ID": contest_id,
                "CONTEST_LISTEN_PORT": 8888,
                "CONTEST_LISTEN_ADDRESS": "0.0.0.0"
            },
            "volumes": common_volumes,
            "networks": ["cms-network"],
            "ports": [f"{port}:8888"],
            "privileged": True,
            "command": f"sh -c \"sleep 5 && cmsContestWebServer {i} -c {contest_id}\""
        }

        domain = item.get("domain")
        if domain:
            service["labels"] = [
                "traefik.enable=true",
                f"traefik.http.routers.cms-contest-{contest_id}.rule=Host(`{domain}`)",
                f"traefik.http.services.cms-contest-{contest_id}.loadbalancer.server.port=8888"
            ]

        compose["services"][svc_name] = service

    with open("docker-compose.contests.generated.yml", "w") as f:
        f.write("# AUTO-GENERATED BY scripts/generate_contest_compose.py\n")
        f.write("# DO NOT EDIT MANUALLY\n\n")
        yaml.dump(compose, f, sort_keys=False)
    
    print(f"Successfully generated docker-compose.contests.generated.yml with {len(compose['services'])} contest(s).")

if __name__ == "__main__":
    generate()
