#!/bin/bash

###############################################################################
# CMS Multi-Contest Compose Generator
# This script generates a docker-compose file for multiple contests
# without requiring heavy dependencies like Python or Bun.
###############################################################################

OUTPUT_FILE="docker-compose.contests.generated.yml"
CONFIG=${CONTESTS_DEPLOY_CONFIG:-"[]"}
# Detect deployment type (img or src)
DEPLOY_TYPE=${DEPLOYMENT_TYPE:-"img"}
CORE_IMAGE="ghcr.io/champyod/cms-docker-core:major-admin-panel"

# Start file content
cat > "$OUTPUT_FILE" << EOF
# AUTO-GENERATED BY scripts/generate-contest-compose.sh
# DO NOT EDIT MANUALLY

services:
EOF

# Extract each JSON object from the array using grep
# This handles [{"id":1,...},{"id":2,...}]
echo "$CONFIG" | grep -o '{[^}]*}' | while read -r line; do
    [ -z "$line" ] && continue
    
    # Extract values using grep and cut
    ID=$(echo "$line" | grep -oE '"id":[[:space:]]*[0-9]+' | cut -d: -f2 | tr -d '[:space:]')
    PORT=$(echo "$line" | grep -oE '"port":[[:space:]]*[0-9]+' | cut -d: -f2 | tr -d '[:space:]')
    DOMAIN=$(echo "$line" | grep -oE '"domain":[[:space:]]*"[^"]*"' | cut -d: -f2 | tr -d '[:space:]"' )
    
    if [ -z "$DOMAIN" ]; then
        DOMAIN="contest-$ID.cms.local"
    fi

    if [ -n "$ID" ] && [ -n "$PORT" ]; then
        cat >> "$OUTPUT_FILE" << EOF
  contest-web-server-$ID:
EOF
        if [ "$DEPLOY_TYPE" = "img" ]; then
            echo "    image: $CORE_IMAGE" >> "$OUTPUT_FILE"
        else
            cat >> "$OUTPUT_FILE" << EOF
    build:
      context: .
      dockerfile: Dockerfile
EOF
        fi

        cat >> "$OUTPUT_FILE" << EOF
    container_name: cms-contest-web-server-$ID
    restart: on-failure:5
    environment:
      CMS_CONFIG: \${CMS_CONFIG:-/usr/local/etc/cms.toml}
      SERVICE_TYPE: ContestWebServer
      SERVICE_SHARD: 0
      CONTEST_LISTEN_PORT: 8888
      CONTEST_LISTEN_ADDRESS: 0.0.0.0
      CONTEST_ID: $ID
      SECRET_KEY: \${SECRET_KEY}
      COOKIE_DURATION: \${COOKIE_DURATION:-10800}
      MAX_SUBMISSION_LENGTH: \${MAX_SUBMISSION_LENGTH:-100000}
      MAX_INPUT_LENGTH: \${MAX_INPUT_LENGTH:-5000000}
      SUBMIT_LOCAL_COPY: \${SUBMIT_LOCAL_COPY:-true}
      NUM_PROXIES_USED: \${NUM_PROXIES_USED:-1}
    volumes:
      - ./config/cms.toml:/usr/local/etc/cms.toml:ro
      - cms-logs:/var/local/log/cms
      - cms-cache:/var/local/cache/cms
      - cms-data:/var/local/lib/cms
      - cms-submissions-$ID:/var/local/lib/cms/submissions
    networks:
      - cms-network
    ports:
      - "$PORT:8888"
    privileged: true
    cgroup: host
    command: >
      sh -c "sleep 10 && cmsContestWebServer 0 -c $ID"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-contest-$ID.rule=Host(\`$DOMAIN\`)"
      - "traefik.http.services.cms-contest-$ID.loadbalancer.server.port=8888"
EOF
    fi
done

if [ $(grep -c "contest-web-server-" "$OUTPUT_FILE") -eq 0 ]; then
    echo "  # No contests configured. Add instances via Admin UI." >> "$OUTPUT_FILE"
fi

# Add footer
cat >> "$OUTPUT_FILE" << EOF

networks:
  cms-network:
    external: true
    name: cms-network

volumes:
  cms-logs:
    external: true
    name: cms-logs
  cms-cache:
    external: true
    name: cms-cache
  cms-data:
    external: true
    name: cms-data
EOF

# Add generated volumes
echo "$CONFIG" | grep -o '{[^}]*}' | while read -r line; do
    ID=$(echo "$line" | grep -oE '"id":[[:space:]]*[0-9]+' | cut -d: -f2 | tr -d '[:space:]')
    if [ -n "$ID" ]; then
        echo "  cms-submissions-$ID:" >> "$OUTPUT_FILE"
        echo "    name: cms-submissions-contest-$ID" >> "$OUTPUT_FILE"
    fi
done

echo "Successfully generated $OUTPUT_FILE"