#!/bin/bash

###############################################################################
# CMS Multi-Contest Compose Generator
# This script generates a docker-compose file for multiple contests
# without requiring heavy dependencies like Python or Bun.
###############################################################################

OUTPUT_FILE="docker-compose.contests.generated.yml"
CONFIG=${CONTESTS_DEPLOY_CONFIG:-"[]"}

# Start file content
cat > "$OUTPUT_FILE" << EOF
version: '3.8'

# AUTO-GENERATED BY scripts/generate-contest-compose.sh
# DO NOT EDIT MANUALLY

services:
EOF

# Parse JSON using sed/grep (no jq required)
# 1. Strip whitespace and quotes
# 2. Split objects into lines
# 3. Iterate and extract values
ITEMS=$(echo "$CONFIG" | sed 's/[[:space:]]//g; s/'.'{//; s/'}'//; s/'},{'}'\n'{'/g')

COUNT=0
if [ "$CONFIG" != "[]" ] && [ -n "$ITEMS" ]; then
    while read -r line; do
        [ -z "$line" ] && continue
        
        # Extract values using regex-like grep/sed
        ID=$(echo "$line" | sed -n 's/.*id:\([0-9]*\).*/\1/p' || echo "")
        # Try both "id":1 and id:1 formats
        if [ -z "$ID" ]; then ID=$(echo "$line" | sed -n 's/.*"id":\([0-9]*\).*/\1/p'); fi
        
        PORT=$(echo "$line" | sed -n 's/.*port:\([0-9]*\).*/\1/p' || echo "")
        if [ -z "$PORT" ]; then PORT=$(echo "$line" | sed -n 's/.*"port":\([0-9]*\).*/\1/p'); fi
        
        DOMAIN=$(echo "$line" | sed -n 's/.*domain:"\([^"]*\)".*/\1/p' || echo "")
        if [ -z "$DOMAIN" ]; then DOMAIN=$(echo "$line" | sed -n 's/.*domain:\([^,}]*\).*/\1/p'); fi
        if [ -z "$DOMAIN" ]; then DOMAIN="contest-$ID.cms.local"; fi

        if [ -n "$ID" ] && [ -n "$PORT" ]; then
            cat >> "$OUTPUT_FILE" << EOF
  contest-web-server-$ID:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-contest-web-server-$ID
    restart: unless-stopped
    environment:
      CMS_CONFIG: 
      SERVICE_TYPE: ContestWebServer
      SERVICE_SHARD: 0
      CONTEST_LISTEN_PORT: 8888
      CONTEST_LISTEN_ADDRESS: 0.0.0.0
      CONTEST_ID: $ID
      SECRET_KEY: 
      COOKIE_DURATION: 10800
      MAX_SUBMISSION_LENGTH: 100000
      MAX_INPUT_LENGTH: 5000000
      SUBMIT_LOCAL_COPY: true
      NUM_PROXIES_USED: 1
    volumes:
      - ./config/cms.toml:/usr/local/etc/cms.toml:ro
      - cms-logs:/var/local/log/cms
      - cms-cache:/var/local/cache/cms
      - cms-data:/var/local/lib/cms
      - cms-submissions-$ID:/var/local/lib/cms/submissions
    networks:
      - cms-network
    ports:
      - "$PORT:8888"
    privileged: true
    cgroup: host
    command: >
      sh -c "sleep 10 && cmsContestWebServer 0 -c $ID"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-contest-$ID.rule=Host(`$DOMAIN`)"
      - "traefik.http.services.cms-contest-$ID.loadbalancer.server.port=8888"
EOF
            COUNT=$((COUNT + 1))
        fi
    done <<< "$ITEMS"
fi

if [ "$COUNT" -eq 0 ]; then
    echo "  # No contests configured" >> "$OUTPUT_FILE"
fi

# Add footer
cat >> "$OUTPUT_FILE" << EOF

networks:
  cms-network:
    external: true
    name: cms-network

volumes:
  cms-logs:
    external: true
    name: cms-logs
  cms-cache:
    external: true
    name: cms-cache
  cms-data:
    external: true
    name: cms-data
EOF

# Add generated volumes
if [ "$CONFIG" != "[]" ] && [ -n "$ITEMS" ]; then
    while read -r line; do
        [ -z "$line" ] && continue
        ID=$(echo "$line" | sed -n 's/.*id:\([0-9]*\).*/\1/p' || echo "")
        if [ -z "$ID" ]; then ID=$(echo "$line" | sed -n 's/.*"id":\([0-9]*\).*/\1/p'); fi
        if [ -n "$ID" ]; then
            echo "  cms-submissions-$ID:" >> "$OUTPUT_FILE"
            echo "    name: cms-submissions-contest-$ID" >> "$OUTPUT_FILE"
        fi
done <<< "$ITEMS"
fi

echo "Successfully generated $OUTPUT_FILE with $COUNT contests."
